# Generated by Django 4.0.1 on 2022-03-27 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_instrument_prescore'),
    ]

    operations = [
        migrations.CreateModel(
            name='audio',
            fields=[
                ('instrumentId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.instrument')),
                ('location', models.FileField(upload_to='')),
            ],
        ),
    ]
