# version: '3.8'
# services:
#   frontend:
#     build: 
#       context: ./
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     depends_on:
#       - backend
#   backend:
#     build: 
#       context: ./src/backend
#       dockerfile: ./Dockerfile
#     ports:
#       - "5000:5000"

# version: '3.8'
# services:
#   frontend:
#     build: 
#       context: ./
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     depends_on:
#       - backend
#   backend:
#     image: my-backend-image
#     build: 
#       context: ./src/python
#       dockerfile: ./Dockerfile
#     ports:
#       - "5000:5000"

version: '3.8'
services:
  frontend:
    image: landucbr/sig-test-backend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    image: landucbr/sig-test-frontend
    ports:
      - "5000:5000"
