# Generated by Django 4.0.1 on 2022-03-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_instrument_prescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='prescore',
            field=models.FloatField(default=0),
        ),
    ]
