[theme]

# Primary accent for interactive elements
primaryColor = '#FFF3FF'

# Background color for the main content area
backgroundColor = '#000000'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#D73F09'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"





#st.markdown("""
#<style>
#div.stButton > button:first-child {
#    background-color: #FFFFFF;
#    secondaryBackgroundColor = '#D73F09';
#    color: #000000;
#    font-size: 20px;
#}
#div.stButton > button:hover {
#    background-color: #D73F09;
#    color:#ff0000;
#    }
#</style>""", unsafe_allow_html=True)